from turtle import *
pensize(20)
pencolor("red")
circle(130)
penup()
goto(-120,50)
pendown()
pencolor("black")
write("100",font=("YouYuan",120,"bold"))
penup()
goto(-110,-90)
pendown()
pencolor("black")
write("限速100",font=("SimHei",50,"bold"))
ht()
